name: Package TrelloExporter for Windows

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Build fat JAR with Maven
        run: ./mvnw clean package

#      - name: Get project version from Maven
#        id: vars
#        run: |
#          $version = & ./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec | Select-String -NotMatch '^\['
#          echo "Extracted version: $version"
#          "version=$version" >> $env:GITHUB_OUTPUT
#        shell: pwsh

#      - name: Setup tmate session
#        if: success() || failure()
#        uses: mxschmitt/action-tmate@v3

#      - name: Show extracted version
#        run: echo "Project version is ${{ steps.vars.outputs.version }}"

      - name: Create EXE with jpackage
        shell: cmd
        run: |
          jpackage ^
            --type exe ^
            --name TrelloExporter ^
            --input target ^
            --main-jar trelloexporter-0.1.0.jar ^
            --main-class com.github.imrezol.trelloexporter.TrelloExporterApplication ^
            --dest dist ^
            --win-console ^
            --runtime-image "%JAVA_HOME%" ^
            --app-version 1.0

      - name: List dist folder contents
        run: dir dist /s
        shell: cmd

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrelloExporter-windows-exe
          path: dist/TrelloExporter-1.0.exe TrelloExporter.exe
